### PR TITLE
Fix recipe dependencies

### PR DESCRIPTION
**Pull request by mrakitin**
Also, partially sync-ing with https://github.com/conda-forge/bluesky-live-feedstock/blob/master/recipe/meta.yaml.

### CODE REVIEW

**Comment by mrakitin** [comment]
I am seeing the following errors in tests:
```py
___________________ ERROR collecting test_build_from_docs.py ___________________
ImportError while importing test module '$PREFIX/lib/python3.9/site-packages/bluesky_live/tests/test_build_from_docs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/tests/test_build_from_docs.py:1: in <module>
    from ..run_builder import (
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/run_builder.py:7: in <module>
    from .bluesky_run import DocumentCache, BlueskyRun
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/bluesky_run.py:9: in <module>
    from .document import Start, Stop, Descriptor
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/document.py:4: in <module>
    from dask.base import normalize_token
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/dask/base.py:15: in <module>
    from tlz import merge, groupby, curry, identity
E   ModuleNotFoundError: No module named 'tlz'
_____________________ ERROR collecting test_run_builder.py _____________________
ImportError while importing test module '$PREFIX/lib/python3.9/site-packages/bluesky_live/tests/test_run_builder.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/tests/test_run_builder.py:6: in <module>
    from ..run_builder import RunBuilder
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/run_builder.py:7: in <module>
    from .bluesky_run import DocumentCache, BlueskyRun
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/bluesky_run.py:9: in <module>
    from .document import Start, Stop, Descriptor
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/document.py:4: in <module>
    from dask.base import normalize_token
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/dask/base.py:15: in <module>
    from tlz import merge, groupby, curry, identity
E   ModuleNotFoundError: No module named 'tlz'
=========================== short test summary info ============================
ERROR test_bluesky_run.py
ERROR test_build_from_docs.py
ERROR test_run_builder.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 0.74s ===============================
```

@danielballan, any pointers?

**Comment by danielballan** [comment]
We might have a hidden `toolz` dependency.

**Comment by mrakitin** [comment]
OK, here is what I've figured out: https://github.com/conda-forge/dask-core-feedstock/pull/93/files in conda-forge gets the missing dependencies, however the version of the package in the `defaults` channel does not have them yet:
image

This is the list of dependencies in the CF package:
image

I'll add those dependencies to this recipe explicitly for now, before it's fixed upstream.

**Comment by danielballan** [comment]
Thanks!

**Pull request merged**
