### PR TITLE
bluesky-live v0.0.8

### PR DESCRIPTION
**Pull request by nsls2forge**
It is very likely that the current package version for this feedstock is out of date.
Notes for merging this PR:
1. Feel free to push to the bot's branch to update this PR if needed.
2. The bot will almost always only open one PR per version.
Checklist before merging this PR:
- [ ] Dependencies have been updated if changed: see [upstream](https://github.com/bluesky/bluesky-live)
- [ ] Tests have passed 
- [ ] Updated license if changed and `license_file` is packaged 

Note that the bot will stop issuing PRs if more than 3 Version bump PRs generated by the bot are open. If you don't want to package a particular version please close the PR.

Here is a list of all the pending dependencies (and their versions) for this repo. The first package is the current feedstock package. Please double check all dependencies before merging.

# Feedstock Packages Build Status

| # | Repo | Build <br/> Health | nsls2forge <br/> PyPI <br/> defaults <br/> conda-forge <br/> GitHub <br/> Versions | Downloads|
|:---:|:-------:|:-----------:|:---------------:|:--------------:|
|1|[bluesky-live](https://github.com/nsls-ii-forge/bluesky-live-feedstock)|[Build Status](https://dev.azure.com/nsls2forge/nsls2forge/_build) <br/> [Code Health](https://landscape.io/github/nsls-ii-forge/bluesky-live-feedstock/master)|[nsls2forge version](https://anaconda.org/nsls2forge/bluesky-live) <br/> [PyPI version](https://pypi.org/project/bluesky-live/) <br/> [defaults version](https://anaconda.org/anaconda/bluesky-live) <br/> [conda-forge version](https://anaconda.org/conda-forge/bluesky-live) <br/> [GitHub version](https://github.com/bluesky/bluesky-live)|[Downloads](https://anaconda.org/nsls2forge/bluesky-live)|

### CODE REVIEW

**Comment by mrakitin** [comment]
I am observing the CI failures on the pytest tests:
```py
+ pytest --pyargs bluesky_live.tests
============================= test session starts ==============================
platform linux -- Python 3.9.5, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: $SRC_DIR
collected 28 items

test_bluesky_run.py .....                                                [ 17%]
test_build_from_docs.py ..                                               [ 25%]
test_run_builder.py ....................F                                [100%]

=================================== FAILURES ===================================
______________________________ test_boolean_data _______________________________

    def test_boolean_data():
        with RunBuilder() as builder:
>           builder.add_stream("primary", data=[True, False, True])

../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/bluesky_live/tests/test_run_builder.py:156: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <bluesky_live.run_builder.RunBuilder object at 0x7f2598cbcb50>
name = 'primary'

    def add_stream(
        self,
        name,
        *,
        data=None,
        data_keys=None,
        uid=None,
        time=None,
        object_keys=None,
        configuration=None,
        hints=None,
    ):
        """
        Define a new stream (table of data) and, optionally add data to it.
    
        Parameters
                }
>               for k, v in data.items()
            }
E           AttributeError: 'list' object has no attribute 'items'
```

@danielballan, was the API changed and the tests did not capture that?

**Comment by danielballan** [comment]
The test was recently added and has a simple usage error. It was probably never run until now. I will delegate to someone the job of finally setting up CI on bluesky-live.

**Comment by danielballan** [comment]
@AbbyGi is on the job!

**Comment by mrakitin** [comment]
I disabled the `pytest` testing, for now, to proceed with packaging.

**Comment by danielballan** [comment]
Thanks. Sorry for the hassle. My fault, obviously.

**Pull request merged**
